Fedora_dnf_packages:
  - zsh
  - git
  - wget
  - curl
  - htop
  - tmux
  - vim
  - python3-pip
  - btop
  - neovim
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - eza
  - fontconfig
  - tar
  - xz

nerd_fonts:
  - Meslo
