---
- name: System set up
  hosts: localhost
  connection: local
  tasks: 

  - name: Display facts
    ansible.builtin.debug:
      var: ansible_facts.keys() | list

  - name: OS specific tasks
    ansible.builtin.include_tasks: "tasks/{{ ansible_facts['distribution'] }}_tasks.yml"
