---

- name: Set user and home directory
  ansible.builtin.set_fact:
    user: "{{ ansible_facts['user_id'] }}"
    home: "{{ ansible_facts['user_dir'] }}"

- name: Install packages with DNF
  ansible.builtin.dnf:
    name: "{{ Fedora_dnf_packages }}"
    state: present
  become: True

- name: Install oh-my-zsh
  ansible.builtin.git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: "{{ home }}/.oh-my-zsh"

- name: Install p10k theme
  block:

    - name: Clone p10k repo
      ansible.builtin.git:
        repo: https://github.com/romkatv/powerlevel10k.git 
        dest: "{{ home }}/.oh-my-zsh/custom/themes/powerelevel10k"

- name: Copy dotfiles
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home }}/.{{ item }}"
    owner: "{{ user }}"
    mode: '0644'
  with_items:
    - zshrc
    - p10k.zsh

- name: Copy ZSH_CUSTOM files
  ansible.builtin.copy:
    src: "zsh_custom/{{ item }}"
    dest: "{{ home }}/.oh-my-zsh/custom/{{ item }}"
  with_items:
    - aliases.zsh
    - vars.zsh
    - quotes

- name: Change default shell to zsh
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/zsh
    state: present
  become: True
