---

- name: Set user and home directory
  ansible.builtin.set_fact:
    user: "{{ ansible_facts['user_id'] }}"
    home: "{{ ansible_facts['user_dir'] }}"

- name: Install packages with DNF
  ansible.builtin.dnf:
    name: "{{ Fedora_dnf_packages }}"
    state: present
  become: True

- name: Install oh-my-zsh
  ansible.builtin.git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: "{{ home }}/.oh-my-zsh"


- name : Install p10k themes
  block: 

  - name: Set p10k location
    ansible.builtin.set_fact:
      p10k_theme_path: "{{ home }}/.oh-my-zsh/custom/themes/powerlevel10k"

  - name: Clone p10k repo
    ansible.builtin.git:
      repo: https://github.com/romkatv/powerlevel10k.git 
      dest: "{{ p10k_theme_path }}"


- name: Install zsh-autocomplete
  block:

  - name: Set zsh-autocomplete path
    ansible.builtin.set_fact:
      zsh_autocomplete_path: "{{ home }}/.zsh/zsh-autocomplete"

  - name: Clone zsh-autocomplete
    ansible.builtin.git:
      repo: https://github.com/marlonrichert/zsh-autocomplete.git
      dest: "{{ zsh_autocomplete_path }}"

- name: Set location for zsh-autosuggestions and zsh-syntax-highlighting
  ansible.builtin.set_fact:
    zsh_autosuggestions_path: /usr/share/zsh-autosuggestions
    zsh_syntax_highlighting_path: /usr/share/zsh-syntax-highlighting

- name: Install Nerd Fonts
  block:

  - name: Create user font directory
    ansible.builtin.file:
      path: "{{ home }}/.local/share/fonts/{{ item }}"
      state: directory
      mode: '0755'
    loop: "{{ nerd_fonts }}"

  - name: Download and extract Nerd Fonts
    ansible.builtin.unarchive:
      src: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.tar.xz"
      dest: "{{ home }}/.local/share/fonts/{{ item }}"
      remote_src: True
      creates: "{{ home }}/.local/share/fonts/{{ item }}/LICENSE.txt"
    loop: "{{ nerd_fonts }}"
    register: nerd_fonts_download

  - name: Refresh font cache
    ansible.builtin.command: fc-cache -f
    when: nerd_fonts_download is changed

- name: Copy dotfiles
  block: 

  - name: Copy .zshrc  
    ansible.builtin.template:
      src: zshrc.j2
      dest: "{{ home }}/.zshrc"
      owner: "{{ user }}"
      mode: '0644'

  - name: Copy p10k config
    ansible.builtin.copy:
      src: p10k.zsh
      dest: "{{ home}}/.p10k.zsh"
      owner: "{{ user}}"
      mode: '0644'

- name: Copy ZSH_CUSTOM files
  ansible.builtin.copy:
    src: "zsh_custom/{{ item }}"
    dest: "{{ home }}/.oh-my-zsh/custom/{{ item }}"
  with_items:
    - aliases.zsh
    - vars.zsh
    - quotes

- name: Change default shell to zsh
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/zsh
    state: present
  become: True
